### ISSUE TITLE
🐞[Bugfix] BRSharedPrefs non-fatal exceptions

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#22]
# Problem

Non-fatal Exception: java.lang.IllegalArgumentException
Unsupported ISO 3166 country: en

`Non-fatal Exception: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: en
       at java.util.Currency.getInstance(Currency.java:371)
       at com.breadwallet.tools.manager.BRSharedPrefs.getIso(BRSharedPrefs.java:45)
       at com.breadwallet.presenter.activities.BreadActivity.lambda$updateUI$11$com-breadwallet-presenter-activities-BreadActivity(BreadActivity.java:395)
       at com.breadwallet.presenter.activities.BreadActivity$$ExternalSyntheticLambda2.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.breadwallet.tools.threads.PriorityThreadFactory$1.run(PriorityThreadFactory.java:23)
       at java.lang.Thread.run(Thread.java:923)`

**Comment by kcw-grunt** [comment]
Recreated the bug 
```
Content-Type: application/json
Accept: application/json
User-agent: Litewallet/738 android/HttpURLConnectionAndroid/14
 X-Litecoin-Testnet: false
Accept-Language: ru
2024-01-26 17:48:42.875  5213-5277  BRWalletManager         com.loafwallet                       D  timber: onBalanceChanged:  4679900
2024-01-26 17:48:42.908  5213-5277  MerkleBlockDataSource   com.loafwallet                       D  timber: merkleBlocks: 1457
2024-01-26 17:48:42.924  5213-5277  PeerDataSource          com.loafwallet                       D  timber: peers: 915
2024-01-26 17:48:43.054  5213-5278  APIClient               com.loafwallet                       D  timber: sendRequest: 
2024-01-26 17:48:43.068  5213-5278  BRSharedPrefs           com.loafwallet                       D  timber: defIso Error: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: ru
```

Fixed  in commit ac8b2b91
